name: Setup Chalk
description: Install chalk and wrap supported commands

inputs:
  version:
    description: |
      Version of chalk to install.
      By default latest version is installed.
      See https://crashoverride.com/releases for all available versions.
    required: false
  load:
    description: |
      Chalk config(s) to load - comma or new-line delimited.
      Can be either paths to files or URLs.
    required: false
  params:
    description: |
      Chalk components params to load.
      Should be JSON array with all parameter values.
      JSON structure is the same as provided by
      'chalk dump params'.
    required: false
  token:
    description: |
      CrashOverride API Token.
      Get your API token at CrashOverride: https://crashoverride.run
    required: false
  password:
    description: |
      Password for chalk signing key.
      Password is displayed as part of `chalk setup`.
    required: false
  public_key:
    description: |
      Content of chalk signing public key).
      Copy from `chalk.pub` after `chalk setup`.
    required: false
  private_key:
    description: |
      Content of chalk signing encrypted private key (with the provided password).
      Copy from `chalk.key` after `chalk setup`.
    required: false

runs:
  using: "composite"
  steps:
    # https://docs.sigstore.dev/system_config/installation/
    - name: Install cosign
      if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: sigstore/cosign-installer@main

    - name: Add Chalk to PATH
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo "$HOME/.chalk/bin" >> $GITHUB_PATH

    - name: Set CHALK_PASSWORD
      if: inputs.password != ''
      shell: bash
      run: |
        echo "CHALK_PASSWORD=${{ inputs.password }}" >> $GITHUB_ENV

    - name: Save Public Key
      if: inputs.public_key != ''
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        CHALK_PUBLIC_KEY: "${{ inputs.public_key }}"
      run: |
        printenv CHALK_PUBLIC_KEY > chalk.pub

    - name: Save Private Key
      if: inputs.private_key != ''
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        CHALK_PRIVATE_KEY: "${{ inputs.private_key }}"
      run: |
        printenv CHALK_PRIVATE_KEY > chalk.key

    - name: Set up chalk
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ./setup.sh \
          --version='${{ inputs.version }}' \
          --load='${{ inputs.load }}' \
          --params='${{ inputs.params }}' \
          --token='${{ inputs.token }}' \
          --prefix=$HOME/.chalk \
          ${{ inputs.public_key != '' && format('--public-key={0}/chalk.pub', github.action_path) || '' }} \
          ${{ inputs.private_key != '' && format('--private-key={0}/chalk.key', github.action_path) || '' }} \
          ${{ runner.debug == '1' && '--debug' || '' }}
