name: Setup Chalk
description: Install chalk and wrap supported commands

inputs:
  version:
    description: |
      Version of chalk to install.
      By default latest version is installed.
      See https://crashoverride.com/releases for all available versions.
    required: false
  load:
    description: |
      Chalk config to load.
      Can be either path to a file or an URL.
    required: false
  params:
    description: |
      Chalk components params to load.
      Should be JSON array with all parameter values.
      JSON structure is the same as provided by
      'chalk dump params'.
    required: false
  token:
    description: |
      CrashOverride API Token.
      Get your API token at CrashOverride: https://crashoverride.run
    required: false

runs:
  using: "composite"
  steps:
    # https://docs.sigstore.dev/system_config/installation/
    - name: Install cosign
      if: runner.os == 'Linux' || runner.os == 'macOS'
      uses: sigstore/cosign-installer@main

    - name: Add Chalk to PATH
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo "$HOME/.chalk/bin" >> $GITHUB_PATH

    - name: Set up chalk
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ./setup.sh \
          --version=${{ inputs.version }} \
          --load="${{ inputs.load }}" \
          --params='${{ inputs.params }}' \
          --prefix=$HOME/.chalk \
          ${{ runner.debug == '1' && '--debug' || '' }}
