steps:
  - label: ":docker: Build and Verify Chalk"
    command: |
      echo "--- :docker: Build with Chalk"
      docker build --load -f .buildkite/Dockerfile.test -t chalk-test:$$BUILDKITE_BUILD_NUMBER .
      echo "--- :chalk: Extract chalk marks"
      chalk extract chalk-test:$$BUILDKITE_BUILD_NUMBER
      echo "--- :label: Docker labels"
      docker inspect --format='{{json .Config.Labels}}' chalk-test:$$BUILDKITE_BUILD_NUMBER
    plugins:
      - ./chalk-buildkite-plugin:
          version: "0.6.5"
