name: setup

on:
  pull_request:

permissions:
  contents: read
  id-token: write

env:
  __CHALK_TESTING__: "true"
  COSIGN_PASSWORD: 6EHvWD1BUk0yWdvm-GGNxA==
  PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfH1ovT0O5dYpileubczT0MQsNsDu
    UhQ1aC2F3S5t48q6bMATGm9IV7Id5/NkUWHjq5mgLX8QhygoSAab+FzEqA==
    -----END PUBLIC KEY-----
  PRIVATE_KEY: |
    -----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
    eyJrZGYiOnsibmFtZSI6InNjcnlwdCIsInBhcmFtcyI6eyJOIjo2NTUzNiwiciI6
    OCwicCI6MX0sInNhbHQiOiJkK0JiMUVzVzhWTXVrekZFRmh0QjJZWGZyMm00ckw2
    MjZGMXc0QWlKVnU0PSJ9LCJjaXBoZXIiOnsibmFtZSI6Im5hY2wvc2VjcmV0Ym94
    Iiwibm9uY2UiOiJGTFNScFNxRDU1UzhyZVc2ZmxuV0JncDFDay9zUFd0QyJ9LCJj
    aXBoZXJ0ZXh0IjoiaUNXbHN4WXFrY0Mvb3JmaVRhRlgwdmpZUDdldDFYSmNlWG5G
    SVZNS0RPMFhsaG13WnkzSWh6VWpYREgvdm1XMFNCMVBkV2lOZDNWZU56VVlkNzZR
    L3JjWmVsRHQyMlh6ZFJsTnpQeXVudDMrcU40aUcyOFc5M2Z0OFZ4b1I2UkZoVUMy
    Y0dNbGMxTFJiMjk4ZXA2bU50WFo0aUxGMm5MYWg1dy8xbTVNeTV5WTZqd2ZHd09z
    MHYzME1uNUhGWDArTm9VQjVzd2U5dUxPZlE9PSJ9
    -----END ENCRYPTED SIGSTORE PRIVATE KEY-----

jobs:
  host:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
          # - runner: self-hosted

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Chalk
        uses: ./
        with:
          password: ${{ env.COSIGN_PASSWORD }}
          public_key: ${{ env.PUBLIC_KEY }}
          private_key: ${{ env.PRIVATE_KEY }}
          load: |
            .github/config.c4m

      - name: Verify Setup
        run: |
          echo 'log_level: "trace"' | sudo tee /etc/chalk.conf
          set -x
          id
          which chalk
          which docker
          strings $(which chalk) | tail -n 30 | grep dadfedabbadabbed | jq
          strings $(which docker) | tail -n 30 | grep dadfedabbadabbed  | jq
          chalk version
          docker version

  container:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}

    container:
      image: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deps
        run: |
          apk add --no-cache curl jq

      - name: Bad Version
        continue-on-error: true
        uses: ./
        with:
          # this version doesnt exist and should fail to download but should
          # show retry logic working
          version: da39a3ee5e6b4b0d3255bfef95601890afd80709

      - name: Bad config
        continue-on-error: true
        uses: ./
        with:
          load: |
            .github/bad_config.c4m
          params: "[]"

      - name: Setup Chalk
        uses: ./
        with:
          password: ${{ env.COSIGN_PASSWORD }}
          public_key: ${{ env.PUBLIC_KEY }}
          private_key: ${{ env.PRIVATE_KEY }}
          load: |
            .github/config.c4m

      - name: Verify Setup
        run: |
          echo 'log_level: "trace"' | tee /etc/chalk.conf
          set -x
          id
          which chalk
          which docker
          strings $(which chalk) | tail -n 30 | grep dadfedabbadabbed | jq
          strings $(which docker) | tail -n 30 | grep dadfedabbadabbed  | jq
          chalk version
          docker version

  crashoverride:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
          # - runner: self-hosted

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Chalk
        uses: ./
        with:
          connect: true
          load: |
            .github/config.c4m

      - name: Verify Setup
        run: |
          echo 'log_level: "trace"' | sudo tee /etc/chalk.conf
          set -x
          id
          which chalk
          which docker
          strings $(which chalk) | tail -n 30 | grep dadfedabbadabbed | jq
          strings $(which docker) | tail -n 30 | grep dadfedabbadabbed  | jq
          chalk version
          docker version
